Contacts Manager/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace Contacts_Manager.Controllers
{
    [Route("[controller]")]
    public class CountriesController : Controller
    {
        //private fields
        private readonly ICountriesService _countriesService;

        //constructor
        public CountriesController(ICountriesService countriesService)
        {
            _countriesService = countriesService;
        }

        [Route("[action]")]
        [HttpGet]
        public IActionResult UploadFromExcel()
        {
            return View();
        }

        [Route("[action]")]
        [HttpPost]
        public async Task<IActionResult> UploadFromExcel(IFormFile excelFile)
        {
            if(excelFile == null || excelFile.Length == 0)
            {
                ViewBag.ErrorMessage = "Please select an xlsx file.";
                return View();
            }

            if(!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                ViewBag.ErrorMessage = "Unsupported file. 'xlsx' file is expected";
                return View();
            }

            try
            {
                int countriesCountInserted = await _countriesService.UploadCountriesFromExcelFile(excelFile);
                ViewBag.Message = $"{countriesCountInserted} countries Uploaded";
            }
            catch (Exception ex) 
            {
                ViewBag.ErrorMessage = ex.Message;
            }
            
            return View();
        }
    }
}

Contacts Manager/Views/Countries/UploadFromExcel.cshtml
@{ 
    ViewBag.Title = "Upload Countries from Excel";
}

<h2>Upload Countries from Excel</h2>
<div class="w-50">
    <form asp-controller="Countries" asp-action="UploadFromExcel" method="post" enctype="multipart/form-data">

        @*ExcelFile*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt">Chose ann xlsx file</label>
            </div>
            <div class="flex-1">
                <input type="file" name="excelFile" class="form-input" />
                <div class="text-red">
                    @ViewBag.ErrorMessage
                </div>
                <div class="text-green">
                    @ViewBag.Message
                </div>
            </div>
        </div>

        <div class="form-field flex">
            <div class="w-25"></div>
            <div class="flex-1">
                <button type="submit" class="button button-blue-back">Upload</button>
            </div>
        </div>

    </form>
</div>