Contacts Manager/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;
using ServiceContracts;
using ServiceContracts.DTO;
using ServiceContracts.Enums;

namespace Contacts_Manager.Controllers
{
    [Route("[controller]")]
    public class PersonsController : Controller
    {
        //private fields
        private readonly IPersonsService _personsService;
        private readonly ICountriesService _countriesService;

        //constructor
        public PersonsController(IPersonsService personsService, ICountriesService countriesService)
        {
            _personsService = personsService;
            _countriesService = countriesService;
        }

        //person list

        [Route("[action]")]
        [Route("/")]
        public async Task<IActionResult> Index(string searchBy, string? searchString, string sortBy = nameof(PersonResponse.PersonName), SortOrderEnum sortOrder = SortOrderEnum.ASC)
        {
            //Search
            //Actual Name - Display name - 
            ViewBag.SearchFields = new Dictionary<string, string>()
            {
                {nameof(PersonResponse.PersonName), "Person Name" },
                {nameof(PersonResponse.Email), "Email" },
                {nameof(PersonResponse.DateOfBirth), "Date of Birth" },

                {nameof(PersonResponse.Gender), "Gender" },
                {nameof(PersonResponse.CountryID), "Country" },
                {nameof(PersonResponse.Address), "Address" }
            };
            Console.WriteLine("fgh");
            //Search
            List<PersonResponse> persons = await _personsService.GetFilteredPersons(searchBy, searchString);


            //Save search fields after searching
            ViewBag.CurrentSearchBy = searchBy;
            ViewBag.CurrentSearchString = searchString;

            //Sort
            List<PersonResponse> sortedPersons = await _personsService.GetSortedPersons(persons, sortBy, sortOrder);
            ViewBag.CurrentSortBy = sortBy;
            ViewBag.CurremtSortOrder = sortOrder.ToString();

            return View(sortedPersons); //Views/Persons/Index.cshtml
        }

        //Executes when th euser clicks on "Create Person" hyperlink 
        [Route("create")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            List<CountryResponse> countries = await _countriesService.GetAllCountries();
            //ViewBag.Countries = countries;
            ViewBag.Countries = countries.Select(temp =>
                new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });

            return View();
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Create(PersonAddRequest personAddRequest)
        {
            //check if person details is valid
            //Sprawdza, czy dane przesłane z formularza są poprawne według walidacji ustawionej w klasie PersonAddRequest
            if (!ModelState.IsValid)
            {
                List<CountryResponse> countries = await _countriesService.GetAllCountries();
                ViewBag.Countries = countries.Select(temp =>
                new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });
                ViewBag.Errors = ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)
                    .ToList();

                return View(personAddRequest);
            }
            //call the service method
            PersonResponse personResponse = await _personsService.AddPerson(personAddRequest);
            //navigate to Index() action method (it makes another get request to "persons/index")
            return RedirectToAction("Index");
        }

        //Edit person details
        [HttpGet]
        [Route("[action]/{personID}")] //Eg: /persons/edit/1
        public async Task<IActionResult> Edit(Guid personID)
        {
            PersonResponse personResponse = await _personsService.GetPersonByPersonID(personID);
            if(personResponse == null) 
                return RedirectToAction("Index");

            List<CountryResponse> countries = await _countriesService.GetAllCountries();
            ViewBag.Countries = countries.Select(temp =>
                new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });

            PersonUpdateRequest personUpdateRequest = personResponse.ToPersonUpdateRequest();
            return View(personUpdateRequest);
        }

        [HttpPost]
        [Route("[action]/{personID}")]
        public async Task<IActionResult> Edit(PersonUpdateRequest personUpdateRequest)
        {
            PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personUpdateRequest.PersonID);

            if(personResponse == null )
                return RedirectToAction("Index");

            //if personResponse is not null and valid
            if (ModelState.IsValid)
            {
               PersonResponse updayedPerson = await _personsService.UpdatePerson(personUpdateRequest);
                return RedirectToAction("Index");
            }

            //if is not valid
            ViewBag.Errors = ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)
                    .ToList();

            return View(personResponse.ToPersonUpdateRequest());

        }


        [HttpGet]
        [Route("[action]/{personID}")]
        public async Task<IActionResult> Delete(Guid? personID)
        {
            PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personID);
            if( personResponse == null )
                return RedirectToAction("Index");

            return View(personResponse);

        }

        [HttpPost]
        [Route("[action]/{personID}")]
        public async Task<IActionResult> Delete(PersonUpdateRequest personUpdateRequest)
        {
            PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personUpdateRequest.PersonID);

            if(personResponse == null )
                return RedirectToAction("Index");

            _personsService.DeletePerson(personResponse.PersonID);
            return RedirectToAction("Index");
        }

        //Generate PDF people list
        [Route("[action]")]
        public async Task<IActionResult> PersonsPDF()
        {
            //Get list of persons
            List<PersonResponse> personResponsesList = await _personsService.GetAllPersons();

            return new ViewAsPdf("PersonsPDF", personResponsesList, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Bottom = 20, Left = 20, Right = 20 },
                PageOrientation  = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }

        //generate csv - people
        [Route("[action]")]
        public async Task<IActionResult> PersonsCSV()
        {
            MemoryStream memoryStream = await _personsService.GetPersonCSV();

            return File(memoryStream, "application/octet-stream", "persons.csv");
        }

        //generate excel - persons
        [Route("[action]")]
        public async Task<IActionResult> PersonsExcel()
        {
            MemoryStream memoryStream = await _personsService.GetPersonsExcel();

            return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "persons.xlsx");
        }
    }
}

Contacts Manager/Views/Persons/Create.cshtml
@model PersonAddRequest
@{ 
    ViewBag.Title = "Create Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons list</a>
<h2>Create Person</h2>

<div class="w-50">
    <form asp-controller="Persons" asp-action="Create" method="post">
        @*Person Name*@
        <div class="form-field flex">
            @*atrybuty for i id współpracują ze sobą, żeby połączyć etykietę (<label>) z odpowiednim polem formularza (<input>)*@
            <div class="w-25">
                @*<label for="PersonName" class="form-label pt">Person Name</label>*@
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                @*<input type="text" class="form-input" id="PersonName" name="PersonName" /> name musi byc takie same jak w kalsie PersonAddRequest*@
                <input asp-for="PersonName" class="form-input" />
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>

        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label">Email</label>
            </div>
            <div class="flex-1">
                @*<input type="email" class="form-input" id="Email" name="Email" />*@
                <input asp-for="Email" class="form-input" />
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>

        @*Date of Birth*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="DateOfBirth" class="form-label">Date of Birth</label>
            </div>
            <div class="flex-1">
                @*<input type="date" class="form-input" id="DateOfBirth" name="DateOfBirth" />*@
                <input asp-for="DateOfBirth" class="form-input" />
                <span asp-validation-for="DateOfBirth" class="text-red"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label">Gender</label>
            </div>
            <div class="flex-1">
                @*<input type="radio" id="Male" name="Gender" value="Male" />*@
                @*<label for="Male">Male</label>*@
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }

                @foreach (string gender in genders)
                {
                    <input type="radio" asp-for="Gender" value="@gender" />
                    <label for="@gender">@gender</label>
                }
                <span asp-validation-for="Gender" class="text-red"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="CountryID" class="form-label">Country</label>
            </div>
            <div class="flex-1">
                @*<select asp-for="CountryID" class="form-input">
            <option value="">Please Select</option>
            @foreach (CountryResponse country in ViewBag.Countries)
            {
                <option value="@country.CountryID">@country.CountryName</option>
            }
        </select>*@
                <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="CountryID" class="text-red"></span>
            </div>
        </div>

        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Address" class="form-label">Address</label>
            </div>
            <div class="flex-1">
                @*<textarea id="Address" name="Address" class="form-input"></textarea>*@
                <textarea asp-for="Address" class="form-input"></textarea>
                <span asp-validation-for="Address" class="text-red"></span>
            </div>
        </div>

        @*ReceiveNewsLetters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                @*<input type="checkbox" id="ReceiveNewsLetters" name="ReceiveNewsLetters" value="true" />*@
                <input type="checkbox" asp-for="ReceiveNewsLetters" value="true"/>
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
                <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
            </div>
        </div>

        @*Submit button*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Create</button>

                <div asp-validation-summary="All" class="text-red">
                    @if (ViewBag.Errors != null)
                    {
                        <div class="text-red ml">
                            <ul>
                                @foreach (string error in ViewBag.Errors)
                                {
                                    <li class="ml">@error</li>
                                }
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </div>
    </form>
</div>
    
@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobtrusive"  asp-fallback-src="~/jquery.validate.unobtrusive.min"></script>
}

Contacts Manager/Views/Persons/Delete.cshtml
@model PersonResponse
@{ 
    ViewBag.Title = "Delete Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons list</a>
<h2>Delete Person</h2>
<h3>Are you sure to this person delete?</h3>

<div class="w-75 center-box">
    <form asp-controller="Persons" asp-action="Delete" method="post">

        <input type="hidden" asp-for="PersonID" />

        @*Person Name*@
        <div class="form-field flex">
            @*atrybuty for i id współpracują ze sobą, żeby połączyć etykietę (<label>) z odpowiednim polem formularza (<input>)*@
            <div class="w-25">
                @*<label for="PersonName" class="form-label pt">Person Name</label>*@
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                @*<input type="text" class="form-input" id="PersonName" name="PersonName" /> name musi byc takie same jak w kalsie PersonAddRequest*@
                <input asp-for="PersonName" class="form-input" disabled="disabled"/>
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>

        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label">Email</label>
            </div>
            <div class="flex-1">
                @*<input type="email" class="form-input" id="Email" name="Email" />*@
                <input asp-for="Email" class="form-input" disabled="disabled"/>
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>

        @*Submit button*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-red-back">Delete</button>

                <div asp-validation-summary="All" class="text-red">
                    @if (ViewBag.Errors != null)
                    {
                        <div class="text-red ml">
                            <ul>
                                @foreach (string error in ViewBag.Errors)
                                {
                                    <li class="ml">@error</li>
                                }
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </div>
    </form>
</div>
    

Contacts Manager/Views/Persons/Edit.cshtml
@model PersonUpdateRequest
@{ 
    ViewBag.Title = "Edit Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons list</a>  
<h2>Edit Person</h2>

<div class="w-75 center-box">
    <form asp-controller="Persons" asp-action="Edit" method="post">

        <input type="hidden" asp-for="PersonID" />

        @*Person Name*@
        <div class="form-field flex">
            @*atrybuty for i id współpracują ze sobą, żeby połączyć etykietę (<label>) z odpowiednim polem formularza (<input>)*@
            <div class="w-25">
                @*<label for="PersonName" class="form-label pt">Person Name</label>*@
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                @*<input type="text" class="form-input" id="PersonName" name="PersonName" /> name musi byc takie same jak w kalsie PersonAddRequest*@
                <input asp-for="PersonName" class="form-input" />
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>

        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label">Email</label>
            </div>
            <div class="flex-1">
                @*<input type="email" class="form-input" id="Email" name="Email" />*@
                <input asp-for="Email" class="form-input" />
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>

        @*Date of Birth*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="DateOfBirth" class="form-label">Date of Birth</label>
            </div>
            <div class="flex-1">
                @*<input type="date" class="form-input" id="DateOfBirth" name="DateOfBirth" />*@
                <input type="date" asp-for="DateOfBirth" class="form-input" />
                <span asp-validation-for="DateOfBirth" class="text-red"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label">Gender</label>
            </div>
            <div class="flex-1">
                @*<input type="radio" id="Male" name="Gender" value="Male" />*@
                @*<label for="Male">Male</label>*@
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }

                @foreach (string gender in genders)
                {
                    <input type="radio" asp-for="Gender" value="@gender" />
                    <label for="@gender">@gender</label>
                }
                <span asp-validation-for="Gender" class="text-red"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="CountryID" class="form-label">Country</label>
            </div>
            <div class="flex-1">
                @*<select asp-for="CountryID" class="form-input">
            <option value="">Please Select</option>
            @foreach (CountryResponse country in ViewBag.Countries)
            {
                <option value="@country.CountryID">@country.CountryName</option>
            }
        </select>*@
                <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="CountryID" class="text-red"></span>
            </div>
        </div>

        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Address" class="form-label">Address</label>
            </div>
            <div class="flex-1">
                @*<textarea id="Address" name="Address" class="form-input"></textarea>*@
                <textarea asp-for="Address" class="form-input"></textarea>
                <span asp-validation-for="Address" class="text-red"></span>
            </div>
        </div>

        @*ReceiveNewsLetters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                @*<input type="checkbox" id="ReceiveNewsLetters" name="ReceiveNewsLetters" value="true" />*@
                <input type="checkbox" asp-for="ReceiveNewsLetters" value="true" />
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
                <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
            </div>
        </div>

        @*Submit button*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Update</button>

                <div asp-validation-summary="All" class="text-red">
                    @if (ViewBag.Errors != null)
                    {
                        <div class="text-red ml">
                            <ul>
                                @foreach (string error in ViewBag.Errors)
                                {
                                    <li class="ml">@error</li>
                                }
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </div>
    </form>
</div>
    
@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobtrusive"  asp-fallback-src="~/jquery.validate.unobtrusive.min"></script>
}

Contacts Manager/Views/Persons/Index.cshtml
@model IEnumerable<PersonResponse>
@{
    ViewBag.Title = "Persons";
}

<!--Aby formularz zebrał wartości z formularza z konkretnego elementu to ten element musi miec name="..."-->
<form asp-controller="Persons" asp-action="Index" method="get">
    <h1>Persons</h1>

    <!--CreateView-->
    <a asp-controller="Persons" asp-action="Create" class="link-hover">Create Person</a>
    <!--PersonsPDF View-->
    <a asp-controller="Persons" asp-action="PersonsPDF" class="link-hover ml">Download as PDF</a>
    <!--PersonsCSV-->
    <a asp-controller="Persons" asp-action="PersonsCSV" class="link-hover ml">Download as CSV</a>
    <!--PersonsExcel-->
    <a asp-controller="Persons" asp-action="PersonsExcel" class="link-hover ml">Download as Excel</a>

    <!--Search-->
    <div class="box flex">
        <div class="flex-1">
            <select class="form-input" name="searchBy">
                @foreach (var field in ViewBag.SearchFields)
                {
                    @if (field.Key == ViewBag.CurrentSearchBy)
                    {
                        <option value="@field.Key" selected="selected" )>@field.Value</option>
                    }
                    else
                    {
                        <option value="@field.Key" )>@field.Value</option>
                    }
                }
                @* searchBy=PersonName&searchString=abc *@
            </select>
        </div>

        <div class="flex-1">
            <!--Value = zachowany stan z wyszukiwania-->
            <input type="search" id="Search" class="form-input" name="searchString" value="@ViewBag.CurrentSearchString">
        </div>

        <div class="flex-1">
            <button class="button button-blue-back">Search</button>
            <a asp-controller="Persons" asp-action="Index" class="link-hover">Clear all</a>
        </div>
    </div>

    <!--Persons List-->
    <table class="table w-100 mt persons">
        <thead>
            <tr>
                <!--Partial View do wyswietlania nazwy kolumn i sortowania-->
                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.PersonName) },
                { "DisplayName", "Person Name" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.Email) },
                { "DisplayName", "Email" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.DateOfBirth) },
                { "DisplayName", "Date of Birth" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.Age) },
                { "DisplayName", "Age" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.Gender) },
                { "DisplayName", "Gender" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.Country) },
                { "DisplayName", "Country" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.Address) },
                { "DisplayName", "Address" },
                })

                @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData) {
                { "ColumnName", nameof(PersonResponse.ReceiveNewsLetters) },
                { "DisplayName", "Receive News Letters" },
                })

                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (PersonResponse person in Model)
            {
                <tr>
                    <td style="width:15%">@person.PersonName</td>
                    <td style="width:20%">@person.Email</td>
                    <td style="width:10%">@person.DateOfBirth?.ToString("dd/MM/yyyy")</td>
                    <td style="width:5%">@person.Age</td>
                    <td style="width:9%">@person.Gender</td>
                    <td style="width:10%">@person.Country</td>
                    <td style="width:13%">@person.Address</td>
                    <td style="width:10%">@person.ReceiveNewsLetters</td>
                    <td style="width:10%">
                        @*/persons/edit/1*@
                        <a asp-controller="Persons" asp-action="Edit" asp-route-personID="@person.PersonID">Edit</a>
                        @*/persons/delete/1*@
                        <a asp-controller="Persons" asp-action="Delete" asp-route-personID="@person.PersonID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

Contacts Manager/Views/Persons/PersonsPDF.cshtml
@model IEnumerable<PersonResponse>
@{
    Layout = null;
}

<link href="~/Stylesheet.css" rel="stylesheet" />
@* http://localhost:port/StyleSheet.css *@

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Persons List</title>
    <style>
        /* Styl CSS dla tabeli */
        table {
            border-collapse: collapse;
            border: 1px solid #ffffff;
            padding: 5px;
            box-shadow: 0px 0px 4px 2px #e4e4e4;
            margin: 10px 0px;
            margin: auto;
        }

        .table thead {
            background-color: #bcd5c6;
            color: #000000;
        }

            .table thead th {
                padding: 5px 10px;
                text-align: left;
            }

        .table tbody td {
            padding: 6px 10px;
        }

        .table tbody tr {
            transition: background-color 0.4s, color 0.3s;
            background-color: #efefef;
            border-bottom: 1px solid #ffffff;
        }

        /* Dodatkowe style */
        h1 {
            text-align: center;
            color: #333;
        }

        .w-100 {
            width: 100%;
        }
    </style>
</head>
<body>

    <!--Persons List-->
    <h1>Persons</h1>
    <table class="table w-100 mt">
        <thead>
            <tr>
                <th>Person Name</th>
                <th>Email</th>
                <th>Date Of Birth</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Country</th>
                <th>Address</th>
                <th>Receive News Letters</th>
            </tr>
        </thead>
        <tbody>
            @foreach (PersonResponse person in Model)
            {
                <tr>
                    <td style="width:15%">@person.PersonName</td>
                    <td style="width:20%">@person.Email</td>
                    <td style="width:13%">@person.DateOfBirth?.ToString("dd/MM/yyyy")</td>
                    <td style="width:9%">@person.Age</td>
                    <td style="width:9%">@person.Gender</td>
                    <td style="width:10%">@person.Country</td>
                    <td style="width:10%">@person.Address</td>
                    <td style="width:20%">@person.ReceiveNewsLetters</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>